### PR TITLE
Upgrade github.com/go-rod/rod to v0.97.12

### LINKED ISSUE #16: Broken dependency
## Bug description
github.com/go-rod/rod v0.92.0 in go.mod is broken.

## Steps to reproduce
1. clone cpt repository
2. go build
3. see an error

## Expected Behaviour
I expect correctly built cpt.

## Error messages/Screenshots (optional)
I got

```
../../../../pkg/mod/github.com/ysmood/leakless@v0.6.12/leakless.go:106:47: undefined: leaklessBin
```

## System Details
 - OS: FreeBSD 12.2-RELEASE
 - Version: master (commit: e51706852f4e97ae433fd23b97b1eb3752230ab1) and v0.16.2 both.

## Any suggestions?
Update github.com/go-rod/rod to v0.97.12 in cpt and cpt-lib. Also, just to check, I tried to fix leakless.go myself: rename leaklessBin to bin did a job and allowed to build your package. But that's not an option. That's an another dependency hell!

### PR DESCRIPTION
**Pull request by igoose1**
## Changelog
Upgrade github.com/go-rod/rod to v0.97.12.

## Fixes issue
Fixes #16.

Should be merged after merging https://github.com/cp-tools/cpt-lib/pull/28. It's better to run `go mod tidy` again before merge.

### CODE REVIEW

**Comment by igoose1** [comment]
I can say easy that's my first contribution in a go project. Couldn't you answer on a little question which can be banal for every mature gopher..?

Go modules are great, well. But how can I build with an edited module on my computer? I've written changes locally but `go build` in cp-tools/cpt (here) wasn't using cp-tools/cpt-lib from ~/go/src. It was trying to fetch v2.2.3 from the network which was impossible as I'm not an owner of the repository and I hadn't pushed v2.2.3 yet. What's the usual way to import from local modules? By "local modules" I mean modules in ~/go/src but not on github or other VCS service.

**Comment by infalmo** [comment]
> Go modules are great, well. But how can I build with an edited module on my computer? I've written changes locally but `go build` in cp-tools/cpt (here) wasn't using cp-tools/cpt-lib from ~/go/src. It was trying to fetch v2.2.3 from the network which was impossible as I'm not an owner of the repository and I hadn't pushed v2.2.3 yet. What's the usual way to import from local modules? By "local modules" I mean modules in ~/go/src but not on github or other VCS service.

https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/

**Comment by infalmo** [comment]
Rather than editing the files in `~/go/src` consider cloning the repo and using this local version as the module (override using the commands given above)

**Comment by igoose1** [comment]
> Rather than editing the files in `~/go/src` consider cloning the repo
> and using this local version as the module (override using the
> commands given above)

Thanks!

-- 
Oskar Sharipov
gpg fingerprint: BAC3 F049 748A D098 A144  BA89 0DC4 EA75 714C 75B5

**Review by infalmo — APPROVED** [review]

**Pull request merged**
